apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: docker.io/library/$TAG:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
